export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const RECEIVE_NO_USER_PROFILE = 'RECEIVE_NO_USER_PROFILE';
export const CLEAR_CURRENT_USER_PROFILE = 'CLEAR_CURRENT_USER_PROFILE';
export const GET_USERS_PROFILES = 'GET_USERS_PROFILES';

export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE';
export const LOAD_COMPANY_PROFILE = 'LOAD_COMPANY_PROFILE';
export const RECEIVE_NO_COMPANY_PROFILE = 'RECEIVE_NO_COMPANY_PROFILE';
export const CLEAR_CURRENT_COMPANY_PROFILE = 'CLEAR_CURRENT_COMPANY_PROFILE';
export const GET_COMPANIES_PROFILES = 'GET_COMPANIES_PROFILES';
